name: Python Package using Conda

on: [push]

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pyepo-build
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Create Conda environment
      run: |
        conda create -n pyepo-build python=${{ matrix.python-version }} conda-build anaconda-client -y
        conda activate pyepo-build
    - name: Build Conda Package
      run: conda build ./pkg -c conda-forge -c pytorch -c gurobi -c default --python ${{ matrix.python-version }}
    - name: Find and upload Conda package
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
      run: |
        CONDA_BLD_PATH=$(conda info --json | jq -r '.conda_prefix')/conda-bld
        echo "Conda build path: $CONDA_BLD_PATH"
        anaconda upload --user pyepo $CONDA_BLD_PATH/*/*.tar.bz2
