name: Python Package using Conda

on: [push]

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9, 3.10, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pyepo-build
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Install Conda-Build and Anaconda-Client
      run: conda install conda-build anaconda-client
    - name: Build Conda Package
      run: conda build ./pkg
    - name: Upload Conda Package
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
      run: |
        find $CONDA_PREFIX/conda-bld/ -name "pyepo-*.tar.bz2" -print0 | xargs -0 -I {} anaconda upload --user pyepo {}

